pipeline:
  lint:
    image: danlynn/ember-cli:3.24.0
    commands:
      - npm run lint:js
      - npm run lint:hbs
      - npm run test:ember
  dummy:
    image: debian
    commands:
      - echo "This is just a dummy step :)"
